<h1>Product</h1>
<section id="creations">
    <?php
    //$this->producten as $producten;
//var_dump($this->producten);
    echo "<article id='product'>";
    echo "<h1>" . $this->producten['title'] . "</h1>";
    echo "<figure>";
    echo "<img src='/images/producten/" . $this->producten['productID'] . "/" . $this->producten['productID'] . ".jpg' alt=" . $this->producten['productID'] . ">";

    echo "</figure>";
    echo "<div id='description'>";
    echo "<p>" . $this->producten['content'] . "</p>";
    echo "</div>";
    echo "<div id='price'>&euro; " . $this->producten['price'] . "</div>";

        //echo "<a href='" . $this->producten['productID'] . "/order'>Bestel</a>";
        
        
     echo "<a href='order/" . $this->producten['productID'] . "'>Bestel</a>";

   //echo "<a href= $this->producten['productID'] . '/order'>Bestel</a>";
   echo '</article>';
    ?>
    <span style="clear:both;display:block;">&nbsp;</span>
</section >