<section id="creations">
    <?php
     $t = Zend_Registry::get("Zend_Translate");

    echo "<article id='product'>";
    echo "<h2>" . $this->producten['title'] . "</h2>";
    echo "<figure>";
    echo "<img src='/images/producten/" . $this->producten['productID'] . "/" . $this->producten['productID'] . ".jpg' alt=" . $this->producten['productID'] . ">";

    echo "</figure>";
    echo "<div id='description'>";
    echo "<p>" . $this->producten['content'] . "</p>";
    echo "</div>";
    echo "<div id='price'>&euro; " . $this->producten['price'] . "</div>";

        //echo "<a href='" . $this->producten['productID'] . "/order'>Bestel</a>";
        
        
     echo "<a href='order/" . $this->producten['productID'] . "'>".$t->translate('product.purchase')."</a>";

   //echo "<a href= $this->producten['productID'] . '/order'>Bestel</a>";
   echo '</article>';
    ?>
    <span style="clear:both;display:block;">&nbsp;</span>
</section >