<section id='creations'>

    <?php
    $t = Zend_Registry::get("Zend_Translate");
    echo "<h1>".$t->translate('basket.overview')."</h1>";
    
    $teller = 1;
    $modulo = 3;
    foreach ($this->producten as $producten) {

//                var_dump($producten);
        //echo "<div class=''> ";
        echo "<article class='article'>";
        echo "<h2>" . $producten['title'] . "</h2>";
        echo "<figure >";
        echo "<img  src='/images/producten/" . $producten['productID'] . "/" . $producten['productID'] . ".jpg' alt=" . $producten['productID'] . ">";

        echo "</figure>";

        echo "<div >";
        echo "<p>" . $producten['teaser'] . "</p>";
        echo "</div>";

        echo "<div id='price'>&euro; " . $producten['price'] . "</div>";

        //echo $this->form;
        echo "<a href='detail/id/" . $producten['productID'] . "'>".$t->translate('product.detail')."</a>";
        echo '</article>';
        // echo "</div> ";
        ?>
    
        <?php
        if ($teller % $modulo == 0) { // bereken of het deelbaar is door drie
            ?>
            <span style="clear:both;display:block;">&nbsp;</span>
            <?php
        }
        $teller++;
    };
        
    
    ?>
    <span style="clear:both;display:block;">&nbsp;</span>
</section >


